/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedCreditCardsIndexRouteImport } from './routes/_authenticated/credit-cards/index'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses/new'
import { Route as AuthenticatedExpensesHistoryRouteImport } from './routes/_authenticated/expenses/history'
import { Route as AuthenticatedExpensesIdRouteImport } from './routes/_authenticated/expenses/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreditCardsIndexRoute =
  AuthenticatedCreditCardsIndexRouteImport.update({
    id: '/credit-cards/',
    path: '/credit-cards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesHistoryRoute =
  AuthenticatedExpensesHistoryRouteImport.update({
    id: '/expenses/history',
    path: '/expenses/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesIdRoute = AuthenticatedExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/expenses/history': typeof AuthenticatedExpensesHistoryRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/credit-cards': typeof AuthenticatedCreditCardsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/expenses/history': typeof AuthenticatedExpensesHistoryRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/credit-cards': typeof AuthenticatedCreditCardsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/_authenticated/expenses/history': typeof AuthenticatedExpensesHistoryRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/credit-cards/': typeof AuthenticatedCreditCardsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/expenses/$id'
    | '/expenses/history'
    | '/expenses/new'
    | '/credit-cards'
    | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/expenses/$id'
    | '/expenses/history'
    | '/expenses/new'
    | '/credit-cards'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/expenses/$id'
    | '/_authenticated/expenses/history'
    | '/_authenticated/expenses/new'
    | '/_authenticated/credit-cards/'
    | '/_authenticated/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit-cards/': {
      id: '/_authenticated/credit-cards/'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof AuthenticatedCreditCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/history': {
      id: '/_authenticated/expenses/history'
      path: '/expenses/history'
      fullPath: '/expenses/history'
      preLoaderRoute: typeof AuthenticatedExpensesHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$id': {
      id: '/_authenticated/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AuthenticatedExpensesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedExpensesIdRoute: typeof AuthenticatedExpensesIdRoute
  AuthenticatedExpensesHistoryRoute: typeof AuthenticatedExpensesHistoryRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedCreditCardsIndexRoute: typeof AuthenticatedCreditCardsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExpensesIdRoute: AuthenticatedExpensesIdRoute,
  AuthenticatedExpensesHistoryRoute: AuthenticatedExpensesHistoryRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedCreditCardsIndexRoute: AuthenticatedCreditCardsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
